### ISSUE TITLE
Minted problems

### ISSUE THREAD

**Issue by willirath** [ExaESM-WP4/texlive-docker#1]
In https://github.com/ExaESM-WP4/JupyterHub-Evaluation-Whitepaper/pull/7/checks?check_run_id=712356126#step:4:596, minted seems to fail.

**Comment by willirath** [comment]
Looks like this is solved with #2 

Needs to be released in order for Dockerhub to build this, though?

**Comment by kathoef** [comment]
We have a rule that triggers builds for the latest version in master. It is currently pending...

**Comment by willirath** [comment]
Ah. That's why https://github.com/ExaESM-WP4/JupyterHub-Evaluation-Whitepaper/runs/720223321 failed. :)
